# Numpy

## Arrays

### Introduction

In [1]:
import numpy as np

 Why is NumPy such an important tool for Science subjects in python? Let's start by looking at one of the most important feautres it has: **The arrays**
 
An array is a data structure that stores values of the **same data type**, in python this is the main difference between arrays and lists but there are some other important differences that will be really useful for us, let's create the examples needed below:

In [2]:
p_list = [1,2,3]
np_arr = np.array(p_list)
print(f'{p_list}\n{np_arr}')

[1, 2, 3]
[1 2 3]


In the cell above we can see that both, lists and arrays can store elements without changing their true value as we will show now:

In [3]:
print(f'First element of the list: {p_list[0]}')
print(f'First element of the array: {np_arr[0]}')
print(f'Sum between first elements of the list and array: {p_list[0] + np_arr[0]}')

First element of the list: 1
First element of the array: 1
Sum between first elements of the list and array: 2


As we said, the main difference between a python list and a NumPy array is that arrays can't store more than one data type, let's check this out:

In [4]:
p_list_data_type = [1, 2, '3']
np_arr_data_type = np.array([1, 2, '3'])

for position in range(len(p_list_data_type)):
    try:
        print(p_list_data_type[position] + np_arr_data_type[positionition])
    except: 
        print(f'The list first item is type: {type(p_list_data_type[position])}')
        print(f'The array first item is type: {type(np_arr_data_type[position])}')
        print("\nYou can't operate with strings and integers!!!")
        break

The list first item is type: <class 'int'>
The array first item is type: <class 'numpy.str_'>

You can't operate with strings and integers!!!


When we try to have more than one data type in the NumPy array, it automatically converts all of its elements to the type it can handle, in this case strings. Why is it happening? The answer of this question will be found in the last  point of the characteristics.

### Characteristics

#### Element-wise operations

Element-wise operetions are performed element by element in a collection of numbers. You can actually perform operations in python basic lists, but they are not **automatically** done, whether on NumPy arrays they are. Here we can see how it works:

In [5]:
# Two equivalent lists are created with the values 1, 2, 3
el_list1 = [1, 2, 3]
el_list2 = el_list1.copy()

# Two equivalent arrays are created with the values 1, 2, 3
el_array1 = np.array(el_list1)
el_array2 = np.array(el_list1)

print(f'Sum of lists: {el_list1 + el_list2}')
print(f'Sum of arrays: {el_array1 + el_array2}')

#We can't actually multiply lists as pyton doesn't knwo
print(f'Multiplication of arrays: {el_array1 * el_list2}')

Sum of lists: [1, 2, 3, 1, 2, 3]
Sum of arrays: [2 4 6]
Multiplication of arrays: [1 4 9]


As we can see, arrays can handle operations for each element by applying operations to themselves, something not enabled with python lists.

#### Multi-dimensional slicing

In lists we can access to the rows of a matrix, but not to rows and columns **at the same time** (different dimensions). That's something we can do in NumPy:

In [23]:
#Create n-dimensional array and transform it into a list
n_dimensional_array = np.random.rand(3,3,3) * 10
n_dimensional_list = n_dimensional_array.tolist()

#Print the matrix
print(n_dimensional_array)

[[[8.74648585 9.15417038 2.985392  ]
  [9.53548579 7.01627598 0.28823439]
  [9.98267791 2.02367793 9.40038867]]

 [[6.64257351 2.19824903 3.35761326]
  [1.98969134 6.16098604 1.21676451]
  [4.33539    4.4162892  8.28803192]]

 [[5.84030532 2.34447405 1.71374356]
  [6.48101167 4.78829637 8.4339782 ]
  [5.52881697 9.16534279 8.07372751]]]


In [27]:
#With this method we can get the last column (and any other, same with rows)
n_dimensional_array[:,:,-1]

array([[2.985392  , 0.28823439, 9.40038867],
       [3.35761326, 1.21676451, 8.28803192],
       [1.71374356, 8.4339782 , 8.07372751]])

What happens with **lists**?

In [28]:
n_dimensional_list

[[[8.746485850216914, 9.154170381259567, 2.985391999376329],
  [9.535485785442178, 7.016275982464472, 0.28823439373173443],
  [9.98267790932502, 2.023677929975344, 9.400388673959135]],
 [[6.642573512788115, 2.1982490285405145, 3.3576132611940537],
  [1.9896913412068573, 6.160986039933421, 1.2167645101322089],
  [4.335390002376698, 4.416289195039951, 8.28803191608387]],
 [[5.840305321249871, 2.34447404574888, 1.7137435630720865],
  [6.481011673777056, 4.788296368782573, 8.43397819515727],
  [5.52881697022202, 9.165342792305431, 8.073727511417253]]]

In [29]:
n_dimensional_list[:][-1] #Slicing the alst column is not possible

[[5.840305321249871, 2.34447404574888, 1.7137435630720865],
 [6.481011673777056, 4.788296368782573, 8.43397819515727],
 [5.52881697022202, 9.165342792305431, 8.073727511417253]]

In [ ]:
[row[2] for row in n_dimensional_list]

With lists, we would need to **create another list** with the values of the columns we are selecting, we are not able to change those values automatically as we can do in NumPy. Also, the process is more complciated, as it varies depending on the shape of the matrix we are trying to slice.

#### Specific object, with specific methods

Let's start by creating an array:

In [69]:
ob_array = np.arange(1,10).reshape(3,3)
print(ob_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### Attributes

###### Array characteristics:

In [ ]:
# Number of elements in the array
print(ob_array.size)

In [ ]:
# Number of dimensions
ob_array.ndim

In [ ]:
# Size of the dimensions of the array
print(ob_array.shape)

In [ ]:
# Data type of the array's elements
ob_array.dtype

In [ ]:
# Transposed array
ob_array.T

There are some extra attributes but we won't explain them as they are not so useful for us, such as the `array.real` or `array.imag`, that takes the real or imaginary numbers from an array. 

###### Memory characteristics:

In [ ]:
# Python buffer object pointing to the start of the array’s data
ob_array.data

In [ ]:
# Information about the memory layout of the array
ob_array.flags

In [ ]:
# Size of the items (its type)
ob_array.itemsize

In [ ]:
# Number of bytes 
ob_array.nbytes

In [ ]:
# Array strides
ob_array.strides

##### Methods

###### Numerical calculations:

In [ ]:
# Return the sum of the elements in a specified axis
ob_array.sum()

In [ ]:
# Return the product of the elements in a secified axis
ob_array.prod()

In [ ]:
# Return the maximum value in the specified axis
ob_array.max()

In [ ]:
# Return the minimum value in the specified axis
ob_array.min()

In [ ]:
# Return the mean value in the specified axis 
ob_array.mean()

In [ ]:
# Return the variance of the elements in a specified axis
ob_array.var()

In [ ]:
# Return the standard deviation of the elements in a specified axis
ob_array.std()

In [68]:
# Return the range of the elements in a secified axis
ob_array.ptp()

NameError: name 'ob_array' is not defined

In [ ]:
# Return the sum of the elements along the diagonal
ob_array.trace()

In [ ]:
# Return the cumulative sum of the elements 
ob_array.cumsum()

In [ ]:
# Return the cumulative product of the elements 
ob_array.cumprod()

###### Array properties, changes and calculations:

In [ ]:
# Reshape the array to change the dimensions and / or their size:
ob_array.reshape(3,3)

In [ ]:
# Return A COPY of the array transofrmed into a 1-D array
ob_array.flatten()

In [ ]:
# Return the array changing its type
ob_array.astype(float)

In [ ]:
# Limits the value in an array
ob_array.clip(2,8)

In [ ]:
# Fills the array with the value given
print(ob_array.fill(5))

In [ ]:
# Creates a copy of the array
ob_array.copy()

In [ ]:
# Dot product of two arrays
ob_array.dot(ob_array)

In [ ]:
# Return the array with the specified axis interchanged
ob_array.swapaxes(0,1)

In [ ]:
# Return an array with the values from the given array specifying their indices
ob_array.take((0,1,8))

In [ ]:
# Rounds every element to X decimals
ob_array.round()

In [ ]:
# Transpose the given array
ob_array.transpose()

In [ ]:
# Return the array transformed into lists
ob_array.tolist()

###### Other and indices:

In [71]:
# Return True if all elements evaluate to True
ob_array.any()

True

In [70]:
# Return True if all elements evaluate to True
ob_array.all()

True

In [ ]:
# Return the indices of the maximum values along an axis
ob_array.argmax()

In [ ]:
# Return the indices of the minimum values along an axis
ob_array.argmin()

In [ ]:
# Return the indices of the elements that are non-zero
ob_array.nonzero()

#### Items stored in contiguous memory

As we saw in the introduction, NumPy arrays are homogeneus (every element is from the same type), but it's not the only rigidity it has, also every array must have a **fixed size**. This means that the shape of every vector must be the same in order to create an efficient matrix. This allows python to store the elements in contiguous memory, which improves the matrices operations performance a lot. let's take a closer look at it:

In [30]:
dt_array = np.array([[0,1,2],[3,4,5,6]])

In [31]:
dt_array

array([list([0, 1, 2]), list([3, 4, 5, 6])], dtype=object)

If we tried to add an element into the second dimension of the array (first or second lsit), pythong would automatically change the dimension types to "object" and would convert the dimensions into lists instead of arrays. 

If we force a dype in the array it would give us an error, as you can't create a matrix with no fixed number of dimensions:

In [34]:
forced_array = np.array([[0,1,2],[3,4,5,6]], dtype = 'int')
print(forced_array)

ValueError: setting an array element with a sequence.

These constraints enable Python to store the array in a single contiguous block of memory. There are two key concepts: **dimensions** and **strides**:

* **Dimensions** are the number of "arrays" or number sequences that the numpy array has.
* **Strides** are the number of bytes you need to step in each dimension when traversing the array.


![](images/np_strides.png)


Strides are the number of bytes to jump-over in the memory in order to get from one item to the next item along each direction/dimension of the array. In other words, it's the **byte-separation** between consecutive items for each dimension. Let's take a look at it:

In [35]:
array = np.arange(1,10).reshape(3,3)
print(f'Array: \n\n{array}')
print(f'\nSize of the elements of the array (in bytes): {array.itemsize}')

Array: 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Size of the elements of the array (in bytes): 4


The size depends on the type of the element, not the element itself, that's why we need homogeneus data, we can check it this way:

In [36]:
array_float = np.array(array, dtype = 'float')
print(f'Array float: \n\n{array_float}')
print(f'\nSize of the elements of the array (in bytes): {array_float.itemsize}')

Array float: 

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Size of the elements of the array (in bytes): 8


So, to go from the first element of the first row to the second, we would need to move through 4 bytes, but what if we wanted to move from the first element of the first row to the first element of the second row?

In this case, we would need to pass through all of the items until we are in the desired row and then keep moving until we find the chosen position. As arrays are fixed size, we know the distance between dimensions will be the same, and so we can conclude that between dimensions (second dimensions, or columns) the stride (number of bytes needed to move through it) will be the `array.itemsize` * size of the previous dimension, in this case:

In [37]:
array.strides

(12, 4)

* **Vertically** (Columns): 3 * 4 -> 12
* **Horizontally** (Rows) : 4 -> 4

The same would happen with more dimensions:

In [38]:
array_3D = np.arange(1,28).reshape(3,3,3)
print(array_3D)
print(f'\n3D array strides: {array_3D.strides}')

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

3D array strides: (36, 12, 4)


* **Depth** : 12 * 3 -> 36
* **Vertically** (Columns): 3 * 4 -> 12
* **Horizontally** (Rows) : 4 -> 4

## Functions

### Array creation:

#### np.array():

In [ ]:
python_list = [1,2,3]
numpy_arr =np.array(python_list)
print(numpy_arr)
# Transforms a python list into an array

#### np.arange():

In [50]:
arange_array = np.arange(0, 10, 2, dtype = 'int')
print(arange_array)
# Creates 1D array from start to stop, you can specify the step

[0 2 4 6 8]


#### np.zeros():

In [ ]:
zero_array = np.zeros((3,5))
print(zero_array)
# Creates n-D array filled with 0's

#### np.ones():

In [ ]:
ones_array = np.ones((3,5))
print(ones_array)
# Creates n-D array filled with 1's

#### np.empty():

In [53]:
empty_array = np.empty((3,5))
print(empty_array)
# Creates n-D array uninitialized

[[ 1.31318365e-311  9.58487353e-322  0.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [ 5.02034658e+175  3.56529231e-057  3.56591469e-057  2.48489075e+184
   7.69125215e+169]
 [ 1.47763641e+248  1.16096346e-028  7.69165785e+218 -5.13320425e-311
   6.50450970e-038]]


#### np.full():

In [54]:
full_array = np.full((3,5), 5)
print(full_array)
# Creates n-D array filled with the given value

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


#### np.eye():

In [58]:
eye_array = np.eye(7)
print(eye_array)
# Return a 2-D array with ones on the diagonal and zeros elsewhere.

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


#### np.linspace():

In [62]:
linspace_array = np.linspace(-4,4, num = 10000)
print(linspace_array)
# Creates 1-D array from start to stop with num items between them

[-4.         -3.99919992 -3.99839984 ...  3.99839984  3.99919992
  4.        ]


#### np.random.random():

In [66]:
np.random.random((3,5,4,4,2))[:,:,:,:,-1]
# Creates n-D random array

array([[[[0.19275932, 0.71700228, 0.28680082, 0.39893346],
         [0.87869912, 0.99596759, 0.61700541, 0.53922615],
         [0.74767157, 0.43596212, 0.81044089, 0.49486707],
         [0.81537202, 0.99980085, 0.39586845, 0.8975325 ]],

        [[0.72923826, 0.70381765, 0.13304393, 0.34859767],
         [0.62549673, 0.00296914, 0.46684912, 0.84353562],
         [0.83183671, 0.18470224, 0.25079893, 0.47616024],
         [0.0308195 , 0.84669943, 0.57516926, 0.54445551]],

        [[0.9708398 , 0.32394543, 0.55198384, 0.12921931],
         [0.49515464, 0.42663272, 0.04194485, 0.14254305],
         [0.57919584, 0.98527831, 0.08108563, 0.29633299],
         [0.15602124, 0.22599107, 0.75604291, 0.11941478]],

        [[0.48197444, 0.99889715, 0.50981305, 0.81690414],
         [0.01033255, 0.94179112, 0.05913236, 0.07643106],
         [0.23140813, 0.42839061, 0.96724318, 0.51767425],
         [0.00290603, 0.0852998 , 0.1382747 , 0.06113009]],

        [[0.64988815, 0.35492019, 0.50155486, 0.

#### np.indices():

In [67]:
indices_array = np.indices((3,5))
print(indices_array)
# Will create a set of arrays per dimension representing its variation

[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]


### Array transformation:

Some of the functions explained before can be used to perform changes in existing lists, specifically **empty**, **zeros** and **ones**, we just need to add **_like**:

In [ ]:
list_to_array = [[1,2,3], [4,5,6]]
function_names = ['empty', 'zeros', 'ones']
for name in function_names:
    function = getattr(np, name + '_like')
    print(f'\nnp.{name}_like(list):\n')
    print(function(list_to_array))

**full** is available too giving the second argument:

In [ ]:
np.full_like(list_to_array, 5)

### Mathematical functions

In this part functions won't have a definition if it's clear what they are or what they do.

Let's define an array to use the functions:

In [40]:
func_arr = np.arange(0,9).reshape(3,3)

#### Trigonometric functions

##### np.sin(arr)

In [ ]:
np.sin(func_arr)

##### np.cos(arr)

In [ ]:
np.cos(func_arr)

##### np.tan(arr)

In [ ]:
np.tan(func_arr)

##### np.arcsin(arr)

In [ ]:
np.arcsin(func_arr)
# Sin go between -1 and 1, so it doesnt make any sense try arcsin with these numbers

##### np.arccos(arr)

In [ ]:
np.sin(func_arr)

##### np.arctan(arr)

In [ ]:
np.sin(func_arr)

#### Rounding

##### np.around(arr)

In [ ]:
np.around(func_arr)

##### np.floor(arr)

In [ ]:
np.around(func_arr)

##### np.ceil(arr)

In [ ]:
np.around(func_arr)

##### np.trunc(arr)

In [ ]:
np.trunc(func_arr)

#### Sums, products, differences

##### np.prod(arr)

In [41]:
np.prod(func_arr)

0

##### np.sum(arr)

In [42]:
np.sum(func_arr)

36

##### np.cumprod(arr)

In [ ]:
np.cumprod(func_arr)

##### np.cumsum(arr)

In [ ]:
np.cumsum(func_arr)

##### np.gradient(arr)

In [ ]:
np.gradient(func_arr)

##### np.cross(arr1, arr2) 

In [ ]:
np.cross(func_arr, func_arr)

##### NaN operations:

We can also apply the sum and product operations to arrays with NaN values treating them as 1's or 0's:

In [ ]:
#sum
print(np.nansum(func_arr))
#prod
print(np.nanprod(func_arr))
#cumsum
print(np.nancumsum(func_arr))
#cumprod
print(np.nancumprod(func_arr))

#### Arithmetic operations

All of the functions here take two lists as mandatory arguments, element-wise: 

##### np.add(arr1, arr2)

In [ ]:
np.add(func_arr, func_arr)

##### np.multiply(arr1, arr2)

In [ ]:
np.multiply(func_arr, func_arr)

##### np.divide(arr1, arr2)

In [ ]:
np.divide(func_arr, func_arr)

##### np.power(arr1, arr2)

In [ ]:
np.power(func_arr, func_arr)

##### np.substract(arr1, arr2)

In [43]:
np.subtract(func_arr, func_arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

##### np.remainder(arr1, arr2)

In [44]:
np.remainder(func_arr, func_arr)

C:\Users\Javier\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

#### Important math functions

##### np.clip(arr, min, max)

In [45]:
np.clip(func_arr, 3,5)

array([[3, 3, 3],
       [3, 4, 5],
       [5, 5, 5]])

##### np.sqrt(arr)

In [ ]:
np.sqrt(func_arr)

##### np.cbrt(arr)

In [ ]:
np.cbrt(func_arr)

##### np.absolute(arr)

In [ ]:
np.absolute(func_arr)

##### np.sign(arr)

In [46]:
np.sign(func_arr)

array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

##### np.maximum(arr1, arr2)

In [47]:
np.maximum(func_arr, func_arr)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### np.minimum(arr1, arr2)

In [ ]:
np.maximum(func_arr, func_arr)

##### np.nan_to_num(arr)

In [48]:
np.nan_to_num(func_arr)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Miscellaneous

### Constants

$\pi$

In [ ]:
np.pi

$e$

In [ ]:
np.e

$\infty$

In [ ]:
np.inf

$NaN$

In [ ]:
np.nan

$None$

In [ ]:
np.newaxis